
# ===== Limited Public Test host and version ======
#application: import-tasks
#version: 1

# ===== Private Alpha Test host and version ======
application: js-tasks-test
version: 1

# ===== Local host ==========
#application: import-tasks-local
#version: 1

runtime: python
api_version: 1

# Static files remain cached by the browser for 12 hours
default_expiration: "12h"


error_handlers:
  - file: error_handlers/error_default.html

  - error_code: over_quota
    file: error_handlers/error_over_quota.html
    
  - error_code: dos_api_denial
    file: error_handlers/error_dos.html
  
  - error_code: timeout
    file: error_handlers/error_timeout.html

    
handlers:
- url: /static
  static_dir: static
  secure: always
  

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: favicon.ico
  secure: always
  
- url: /info
  static_files: static/info.html
  upload: info.html
  secure: always
  
- url: /worker
  script: worker.py
  login: admin
  secure: always

- url: /admin/.*
  script: import_tasks.py
  login: admin
  secure: always

# Main page does not require login, so that anyone can read main page before authorising
- url: /
  script: import_tasks.py
  secure: always

# Subsequent pages require user to be logged in
- url: /.+
  script: import_tasks.py
  login: required
  secure: always

# ============================
# For debug on localhost
# ============================
#- url: /oauth2callback
#  script: oauth2client/appengine.py
